#!/bin/sh

set -e

export GOOS=noos

case "$GOTARGET" in
stm32*|nrf5*)
	export GOARCH=thumb
	;;
k210)
	export GOARCH=riscv64
	;;
*)
	echo "unknown GOTARGET: '$GOTARGET'"
	exit 1
	;;
esac

if [ -z "$IRQNAMES" ]; then
	case "$GOTARGET" in
	stm32*)
		IRQNAMES=github.com/embeddedgo/stm32/hal/irq
		;;
	nrf5*)
		IRQNAMES=github.com/embeddedgo/nrf5/hal/irq
		;;
	k210)
		IRQNAMES=github.com/embeddedgo/kendryte/hal/irq
		;;
	esac
	IRQNAMES=$(go list -tags $GOTARGET -f '{{.Dir}}' $IRQNAMES)
fi

{
	echo '// DO NOT EDIT THIS FILE. GENERATED BY build.sh.'
	echo
	echo 'package main'
	echo
	echo 'import _ "unsafe"'
	echo
	while read name a1 a2 a3 rest; do
		if [ "$a1" = '=' ]; then
			echo "//go:linkname ${name}_Handler IRQ${a2}_Handler"
		elif [ "$a2" = '=' ]; then
			echo "//go:linkname ${name}_Handler IRQ${a3}_Handler"
		fi
	done <"$IRQNAMES/$GOTARGET.go"
} >zisrnames.go

name=$(basename $(pwd))

ldflags="-M $GOMEM"
if [ -n "$GOTEXT" ]; then
	ldflags="$ldflags -T $GOTEXT"
fi

if [ -z "$GOBIN" ]; then
	GOBIN=go
fi

$GOBIN build -tags $GOTARGET -ldflags "$ldflags" -o $name.elf $@

rm -f zisrnames.go

rm -f $name.hex $name-settings.hex $name.bin
case "$GOOUT" in
hex)
	arm-none-eabi-objcopy -O ihex $name.elf $name.hex
	;;
bin)
	arm-none-eabi-objcopy -O binary $name.elf $name.bin
	;;
esac
